// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASm0E9IVi7lf0rLbkZa4NIEN2YIw_HjuY',
    appId: '1:143820315515:web:473cc1627503a426b4bbde',
    messagingSenderId: '143820315515',
    projectId: 'agrimarket-de899',
    authDomain: 'agrimarket-de899.firebaseapp.com',
    storageBucket: 'agrimarket-de899.firebasestorage.app',
    measurementId: 'G-XDSNYVT4BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNQNX_U0A6U_lKSrE3ko2nce1SflTD8mA',
    appId: '1:143820315515:android:98fc344cd6711c73b4bbde',
    messagingSenderId: '143820315515',
    projectId: 'agrimarket-de899',
    storageBucket: 'agrimarket-de899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLy_OP9EGXlq3yOGKPzWbtw0Ae4PEQsZQ',
    appId: '1:143820315515:ios:70d772fd5c8bba9ab4bbde',
    messagingSenderId: '143820315515',
    projectId: 'agrimarket-de899',
    storageBucket: 'agrimarket-de899.firebasestorage.app',
    iosBundleId: 'com.example.agrimarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLy_OP9EGXlq3yOGKPzWbtw0Ae4PEQsZQ',
    appId: '1:143820315515:ios:70d772fd5c8bba9ab4bbde',
    messagingSenderId: '143820315515',
    projectId: 'agrimarket-de899',
    storageBucket: 'agrimarket-de899.firebasestorage.app',
    iosBundleId: 'com.example.agrimarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASm0E9IVi7lf0rLbkZa4NIEN2YIw_HjuY',
    appId: '1:143820315515:web:81f1985d25fa9001b4bbde',
    messagingSenderId: '143820315515',
    projectId: 'agrimarket-de899',
    authDomain: 'agrimarket-de899.firebaseapp.com',
    storageBucket: 'agrimarket-de899.firebasestorage.app',
    measurementId: 'G-JY4BD69EC6',
  );
}
